### ISSUE TITLE
Trazando projetos de lei

### ISSUE THREAD

**Issue by ppKrauss** [okfn-brasil/trazdia#19]
Os metadados dos projetos de Lei do Senado estão bem estrutirados.
Veja o XML dessa PEC por exemplo, http://legis.senado.leg.br/dadosabertos/materia/PEC/55/2016

Ver dicas em [DiscussOKBr/4464](https://discuss.okfn.org/t/4464):

*  `GET /materia/{sigla}/{numero}/{ano}`
*  `GET /materia/textos/{codigo}`

**Comment by JaTvoiRabotnik** [comment]
Mudando para wiki, como discussao de estrutura de API.
