### ISSUE TITLE
Reféns do conceito de refém

### ISSUE THREAD

**Issue by ppKrauss** [okfn-brasil/trazdia#21]
(o título já dá a dica: esta *issue* é uma discussão meramente filosófica! ... Se vingar passo pro Medium)

## Dilema das *embedded languages*

Sempre que resolvemos desenvolver um sistema fazendo uso de uma determinada linguagem (Java, Javascript, Python, PHP, etc.), estamos excluindo certas soluções que existem apenas em outra linguagem. 

O tratamento de *queries* em documentos e *queries* em bancos de dados é o caso clássico: existem *query languages* já bem padronizadas (independentes!) e com implementações (*engines*) bastante eficientes.  As *query languages* são um grupo particular de [*Domain-specific languages*](https://en.wikipedia.org/wiki/Domain-specific_language), também ditas **mini-languages**, enquanto a linguagem de desenvolvimento do sistemão como um todo, é uma [linguagem de propósito geral](https://en.wikipedia.org/wiki/General-purpose_language) (abreviaremos **general-language**).
 
Para se ter o melhor dos mundos, adota-se a  estratégia de embutir a mini-language dentro da general-language, como se fosse uma chamada de função, onde o parâmetro é uma expressão escrita em mini-language. Nesta situação, para o caso SQL temos a [*embedded* SQL](https://en.wikipedia.org/wiki/Embedded_SQL). Esse tem sido por décadas, dos anos 1970 até hoje, o paradigma de implementação do "diálogo" entre sistemas e respectivos bancos de dados.
 
Com o avanço e consolidação das [metodologias ágeis](https://en.wikipedia.org/wiki/Agile_software_development), as *abstrações* de banco de dados &mdash; para "esconder o SQL" do programador e tornar seu trabalho mais ágil &mdash;, ganharam força *frameworks* ágeis como Python Django, Java Spring e CakePHP... 

## Analogia jQuery

Em jQuery, o *framework* Javascript que inclui uma *mini-language* de [CSS-selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors),  ficam evidentes casos clássicos (ver [pageviews aqui](https://stackoverflow.com/q/7938259/287948)) como <br/>&nbsp; `$("div:not(#myid)")` ou `$("div").not("#myid")`<br/>qual seria mais eficiente? Qual seria mais legível para o programador?
O melhor é concentrar tudo na *mini-language* seletora ou criar uma cadeia de filtros na *general-language*?

* `$("div:not(#myid)")` - Expressa tudo dentro da *mini-language*.
* `$("div").not("#x")` - Apenas "átomos seletores" na *mini-language*, o  método *not()* está expresso em *general-language*.

Existem elementos do algoritmo, como o método *not()* do exemplo, que podem ser internalizados na _mini-language_ ou externalizados para _general-language_. Com todo avanço e elegância conquistados por jQuery, permanece o antigo **dilema de internalizar ou externalizar**.

Haverá sempre uma disputa, e portanto o que restam são escolhas difíceis para lidar com essa disputa… Escolhas da empresa:

1. ser **indiferente** e aceitar que o uso de ambas é válido, permitindo para sempre que os programadores possam ignorar o fato de trechos de código terem “sinônimos” na outra linguagem. <br/> GESTÃO: a decisão caberia exclusivamente ao (gosto do) programador, e aos demais, caberia o respeito a essa decisão inicial.

2. não ignorar, e **tomar partido** por uma delas para padronizar internamente o projeto.
GESTÃO: à empresa ou coordenador de projeto caberia a decisão inicial de escolher uma das formas (internalizada ou externalizada) e daí em diante exigir que todos respeitem essa decisão.

3. … não ignorar, mas deixar para depois os problemas de performance ou estilo. <br/>GESTÃO: _**go-horse** process_!

Ser indiferente (opção-1) é o mais natural, mas a demanda por otimizações pode levar a tomar partido mais cedo ou mais tarde. Aí, o problema é justificar o partido tomado, caso a caso… Um sonho seria, ainda na opção-1, adotar um compilador que transforme os trechos de código quando for oportuna uma otimização… Obrigar os programadores a validarem o código é visto hoje em dia como boa prática, não criaria risco de tirania, arbitrariedade ou conflito pessoal, como na opção-2.

Assim "pra já", não temos esse compilador... E quando existir, precisará ser configurado para tomar decisões de priorizar performance ou priorizar legibilidade e manutenibilidade do código… E ao impor um estilo que torna certos  programadores mais produtivos e outros menos, acaba trazendo de volta o dilema. 

Voltando à opção-2, ela é muito melhor do que a opção-3: transparência e clareza de contrato é sempre preferível ao caos, falta de planejamento e retrabalhos aleatórios.

Com essa ilustração podemos concluir o seguinte: por hora temos que encarar o problema. Sonhar com a automação não adianta, mesmo porque todos os dias a complexidade aumenta e a solução ideal fica mais distante.

## Motivações das abstrações SQL

Com o avanço e consolidação das [metodologias ágeis](https://en.wikipedia.org/wiki/Agile_software_development), os *frameworks ágeis* e suas as abstrações de SGBD, em Python Django, Java Spring, CakePHP, etc. ganharam força. Hoje os *frameworks* são quase que obrigação em grandes projetos.

A motivação inicial das abstrações de SGBD, no sentido de “esconder o SQL do programador", era tornar seu trabalho mais ágil quando o SQL não fosse complexo, principalmente na persistência de dados. <br/>PS: o perigo da "injeção de SQL" é só oportunismo, não será considerada motivação real. 

Historicamente a abstração de banco de dados (Sistema de Gerenciamento de Banco de Dados  -  SGBD) teve uma outra forte motivação: o **estado de refém em que se encontravam as fábricas de software** com relação aos grandes fornecedores de SGBD (Oracle, Microsoft, etc.) e a diversidade e instabilidade das “soluções free”. Ser refém de um fornecedor de SGBD, como Oracle ou Microsoft, significa ser colonizado por sua cultura e ser obrigado a pagar por licenças proprietárias… E além disso, ser obrigado a limitar seus algoritmos para seguir em conformidade com as fraquezas dos produtos do fornecedor.

## Opção-1 de indiferença
Apenas listando  problemas conhecidos com a liberdade de ser indiferente:
* retrabalho aleatório infinito: um programador "corrige" o a opção do outro.
* redução da legibilidade e   manutenibilidade do código por não seguir um estilo padrão.
* risco de gastar tempo inutilmente discutindo algo que se mistura ao problema da não-padronização. 
* ...

## Opção-2 de tomar partido

Apenas listando  problemas conhecidos com a falta de liberdade ao se obrigar um estilo:

* uso de "regras cegas" é inútil, uso de "regras contextualizadas" cria custo posterior de treinamento e auditoria.
* dificuldade de esclarecer novos programadores sobre opções adotadas
* conflitos que seriam dos programadores se tornam gerenciais,  e surge risco do projeto inteiro ser refatorado por uma mudança de decisão na gestão.
* ...

## Solução sugerida 

1. Esclarecer com clareza a previsão de SQL do backend.<br/>(falta decidir por exemplo existirá outra opção ao PostgreSQL 9.5+ e qual seria essa opção)

1. Esclarecer com clareza a separação entre backend e frontend<br/>(as opções de persistência de dados exclusivos do frontend não afetam o backend). 
 
1. Componentizar o sistema em microservices e webservices <br/>(decisão já tomada em consenso).

1. Métodos ágeis para a configuração das APIs, partindo das respectivas especificação [OpenAPI](https://www.openapis.org/).<br/>(decisão já tomada em consenso).

2. Adotar a mesma *general-language* (no caso Python) no SGBD quando da implementação de stored procedures com algoritmos gerais das regras de negócio, e reutilizar as funções a partir de uma biblioteca comum.

3. Adotar PostgREST ou similar para implementação dos microservices mais simples, tais com "name resolvers" 

4. Adotar SQL-VIEWs padronizadas para simplificar a oferta de dados conforme demanda, ao invés de desenhar queries complexas no sistema (na general-language).

5. Classe "commander" na general-language para as operações e web-services mais complexos.<br/>(decisão já tomada em consenso).  <br/>Na classe commander e demais algoritmos do sistemão, usar a opção de **obrigar o uso do framework** (proibir código SQL explícito), exceto quando não existe (por exemplo alguma limitação no acesso a campos JSONb). 
 
6. Prever na general-language o uso de chamadas diretas aos microservices (item 3) por SQL, sem demanda por intermediação HTTP.

**Comment by JaTvoiRabotnik** [comment]
Nao e um issue. Transferido para uma Wiki.
