### ISSUE TITLE
Modelo inicial para fase1 do projeto

### ISSUE THREAD

**Issue by ppKrauss** [okfn-brasil/trazdia#22]
Modelo de dados inicial, para a primeira fase do projeto Trazdia e de produção do OFICIAL.NEWS,

![ [](https://yuml.me/b81162fa) ](https://yuml.me/b81162fa)

```
[Jurisdição|-id;name;lexname;abbrev]
[Autoridade|-id;name;lexname;abbrev]
[Editora|-cnpj;name;abbrev;info:JSON]
[Fascículo| -id; oficial_id; data; seq; oficial_url; info:JSON]
[Contrato|contrato_url;contrato_valor;contrato_fracao]

[Jurisdição]1---*[Autoridade]
[Jurisdição]<>---1..*[SubJurisdição]
[Jurisdição]^-[SubJurisdição]

[Autoridade]^-[Contratante]

[Periodico|-issn;name;abbrev;isDiario;info:JSON]
[DiarioOficial|-id;name;abbrev;info:JSON]

[Jurisdição]1---*[DiarioOficial]
[Contratante]1---1..*[Contrato]
[Editora]---1..*[Contrato]
[Periodico]++-1>[DiarioOficial]
[Periodico]^-[Específico]
[DiarioOficial]++-1..*>[Fascículo]
[Contrato]<>---1..*[Fascículo]
[Editora]<>---1..*[Periodico]
```

A autoridade vinculada ao diário é uma "autoridade emitente de documentos oficiais", via de regra entidade do Poder Executivo, mas aqui estamos catalogando qualquer forma de publicação que desempenhe o "papel de diário oficial", mesmo não sendo designado "diário", como no caso da publicação de acórdons pelo Poder Judiciário.

A especialização *Específico* de *Periódico* indica que um periódico pode ser "container" de um ou mais Diários Oficiais, sem ser ele mesmo, o periódico, o Diário Oficial. Essa situação foi comum durante décadas nos municípios pequenos do Brasil, com menos de 1 milhão de habitantes, que usavam páginas ou encartes de jornais de maior circulação da cidade para publicar o diário oficial.

**Comment by JaTvoiRabotnik** [comment]
Perfeito, bora transformar em wiki, na pagina de arquitetura de dados.

**Comment by JaTvoiRabotnik** [comment]
Fechando como um nao-issue. Arquitetura de sistema. Transferido para wiki.
