### ISSUE TITLE
Metas

### ISSUE THREAD

**Issue by ppKrauss** [okfn-brasil/trazdia#6]
Usando este esta issue como espaço de discussão para as metas,
 https://github.com/okfn-brasil/trazdia/milestones

Por exemplo:

1. Trazer o Diário do Rio para suprir o QueriDO

2. Trazer o Diário-retranca do Diário Livre, para aproveitar infra já montada.

3. Trazer outros diários HTML oficiais.

4. Planejar o caso dos PDFs.

Também tem kanban da gestão de metas, https://github.com/okfn-brasil/trazdia/projects
só falta discutir aqui nesta issue outras metas, principalmente aquelas que garantem soma de esforços com o [QueriDO](github.com/okfn-brasil/queriDO).

**Comment by JaTvoiRabotnik** [comment]
Fechando esse issue e mudando para uma discussao de Wiki.
