### ISSUE TITLE
Metadados fundidos e metadados externos

### ISSUE THREAD

**Issue by ppKrauss** [okfn-brasil/trazdia#8]
Contexto: na conversão ou "reempacotamento" do HTML, ou seja, quando se tratar de HTML (e **não** de PDF ou TXT). 

## Proposta, fundamento e justificativa ##

Como em outros periódicos típicos, o Diário Oficial apresenta em seu **[*front*](https://jats.nlm.nih.gov/publishing/tag-library/1.1/element/front.html)** metadados da matéria (artigo) relativos: 

* ao próprio diário como um todo e o fascículo em que se insere o artigo, ditos **[journal-meta](https://jats.nlm.nih.gov/publishing/tag-library/1.1/element/journal-meta.html)**, que se repetem em todas as matérias do fascículo,  portanto podem ser "externos" à matéria, ou serem repetidos nela, mesmo sem terem sido explicitados no conteúdo original da matéria. Daí este tipo de dado vem "escondido" em Javascript ou XML junto com o restante da matéria.

* à matéria em questão, como  **[article-meta](https://jats.nlm.nih.gov/publishing/tag-library/1.1/element/article-meta.html)**: idealmente o conteúdo da matéria já tem em si o título, ID, autores, resumo, etc. Neste caso o metadado  deve vir fundido ao conteúdo, como marcação [Microdata](https://en.wikipedia.org/wiki/Microdata_(HTML)). <br/> Ela permite destacar cada metadado diretamente do conteúdo apresentado ao leitor, *não* existe adição de conteúdo extra (e iconsistente com original) nem duplicação de conteúdo para satisfazer diferentes representações (ex. HTML e Javascript).

## Modelagem como Strategy

Seguindo o *pattern strategy* usual

![](https://upload.wikimedia.org/wikipedia/commons/3/39/Strategy_Pattern_in_UML.png)

* No primeiro caso, *journal-meta*, os algoritmos das ConcreteStrategies  podem trazer os dados ou do chamado "template da matéria", da sua URL (em alguns raros o endereço vem com os metadados) ou de alguma API adicional (oferecida pelo Diário)  utilizada para esse fim.

* No segundo caso, *article-meta*, os algoritmos das ConcreteStrategies  **devem** realizar o *parsing* do conteúdo para entregar o código HTML já marcado com  Microdata, ou seja, com os metadados já fundidos ao conteúdo.

## Modelagem de dados
 
![](https://github.com/okfn-brasil/trazdia/raw/master/include/trazDia-arqDados1.png)

O modelo expressa o formato de armazenamento e de intercâmbio de dados. Em particular o campo *conteudo* da entidade "objeto", por ser  HTML5 poliglota, é armazenado como XML, e justamente por isso os metadados de *article-meta* podem ser recuperados por XPath (e podem alternativamente ficar em cache JSON), e os *journal-meta* como JSON no atributo *fasciculo.info*.

PS: ver [modelo de dados geral na Wiki do queriDO](https://github.com/okfn-brasil/queriDO/wiki/Modelo-de-dados)

**Comment by JaTvoiRabotnik** [comment]
Fechado - não é um issue. [Tramnsformado em wiki](https://github.com/okfn-brasil/trazdia/wiki/Arquitetura:-Metadados-fundidos-e-metadados-externos).
