### ISSUE TITLE
Garantias e obrigações do TrazDia

### ISSUE THREAD

**Issue by ppKrauss** [okfn-brasil/trazdia#9]
Em geral softwares públicos se eximem de qualquer compromisso ou responsabilidade... Mas no caso de gestão de transparência, compressão, gestão de backups, etc. requerem ao menos certificação de terceiros atestando que fazem o que prometem.

## Sugestão/Rascunho

**Garantia-1**:  O TrazDia não cria, edita ou altera o conteúdo exibido. 

Explicação: todo o processo de coleta de dados cujo resultado culmina nas informações oferecidas é realizado automaticamente, através de fontes públicas indicadas. Portanto, o TrazDia não substitui as fontes originárias da informação, não garante a veracidade dos dados nem que eles estejam atualizados, exceto pelas informações copiadas da fonte.

**Garantia-2**: Garantia de que o conteúdo apresentado neste instante por um dado Diário Oficial, tem os mesmo conteúdo que um conteúdo previamente fornecido.   Garantias de 1) equivalência byte-a-byte;  2) equivalência por XML C14N; 3) equivalências por hash (SHA1, SHA3, etc.).

...

**Comment by JaTvoiRabotnik** [comment]
Fechado - não é um issue. [Transformado em Wiki](https://github.com/okfn-brasil/trazdia/wiki/Feature:-Get-index-of-pages-for-one-edition).
